config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|sv/ do
    resources :tasks do
      member do
        post 'register'
      end
    end

    devise_for :users

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"

    get "pages/home"
    root "pages#home"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  has_many :task_categories, dependent: :destroy
  has_many :categories, through: :task_categories

  validates :title, presence: true
  validates :company, presence: true

  accepts_nested_attributes_for :categories
end

app/models/task_category.rb
class TaskCategory < ApplicationRecord
  belongs_to :task
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    @task_count = Task.count
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /tasks
     def index

    base_tasks = Task.all

    if params[:category_ids].present?
      base_tasks = base_tasks.joins(:categories).where(categories: { id: params[:category_ids] })
    end

    if params[:sort] == "asc"
      @tasks = base_tasks.order(created_at: :asc)
    elsif params[:sort] == "desc"
      @tasks = base_tasks.order(created_at: :desc)
    else
      @tasks = base_tasks.order(created_at: :desc)
    end

    @pagy, @tasks = pagy(@tasks, items: 10)
  end


  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to @task, notice: t("tasks.create.success")
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: t("tasks.update.success")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: t("tasks.destroy.success")
  end

  # email registration for task
  def register
    @task = Task.find(params[:id])
    if user_signed_in?
      UserMailer.with(task: @task, user: current_user).task_registration_email.deliver_now
      redirect_to @task, notice: "Du har anmält dig till uppdraget!"
    else
      redirect_to @task, alert: "Du måste vara inloggad för att anmäla dig."
    end
  end

  before_action :find_or_create_category, only: [:create, :update]

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :company, :city, :description)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    redirect_to tasks_path, notice: "Not authorized to edit this task" if @task.nil?
  end

  def find_or_create_category
    if params[:task][:new_category_name].present?
      category_name = params[:task][:new_category_name]
      category = Category.find_or_create_by(name: category_name)
      params[:task][:category_ids] ||= []
      params[:task][:category_ids] << category.id
    end
  end

  def task_params
    params.require(:task).permit(:title, :company, :city, :description, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    BRAND_NAME = "Volontärbyrån"
    
    include Pagy::Frontend
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<header>
  <div class="header-inner-wrapper">

      <div id="logo-menu-container">
        <%= link_to root_path do %>
              <img id="header-logo" src="/logo-black.svg" alt="Volontärbyrån logo" />
          <% end %>
          <nav>
            <ul id="header-menu">
            <li>
                <%= link_to "För volontärer", root_path %>
            </li>
            <li>
                <%= link_to "För organisationer", root_path %>
            </li>
            <li>
                <%= link_to "Alla uppdrag", tasks_path %>
            </li>
            <li>
                <%= link_to "Om oss", root_path %>
            </li>
            </ul>
          </nav>
      </div>

      <div class="header-cta-container-wrapper">
      <div class="header-cta-container">
        <% if user_signed_in? %>
          <%= link_to "Skapa uppdrag", new_task_path, class: "primary-cta" %>
          
          <%= button_to "Logga ut", destroy_user_session_path, method: :delete, class: "primary-cta" %>
        <% else %>
        
        <div class="cta-horizontal-wrapper">
          <%= link_to "Skapa konto", new_user_registration_path, class: "primary-cta" %>
          
          <%= link_to new_user_session_path, class: "primary-cta" do %>
            <span>logga in </span>
          <% end %>
          </div>
        <% end %>
          
      
        </div>    
        <% if user_signed_in? %>
            <p class="logged-in-user-email">
              <%= t("header.logged_in_as", email: current_user.email) %>
            </p>
          <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= content_for(:title) || ApplicationHelper::BRAND_NAME %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <%= vite_stylesheet_tag "application" %>
  <%= vite_javascript_tag "application" %>
  
  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%= yield :head %>

</head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="primary-background" id="home-tasks-container">
  <% if @task_count == 0 %>
    <h1>Just nu finns det inga uppdrag.</h1>
  <% else %>
    <h1>Just nu finns det <%= @task_count %> uppdrag</h1>
    <p id="home-tasks-link"><%= link_to "Se alla våra uppdrag", tasks_path %></p>
  <% end %>
</div>

app/views/tasks/_filter.html.erb
<%= form_with url: tasks_path, method: :get do %>
    <div class="filter-wrapper">
        <div class="filter-wrapper">
            <p class="filter-heading">Kategorier</p>

            <div class="filter-items">
                <% Category.all.each do |category| %>
                    <div class="filter-item">
                    <%= check_box_tag "category_ids[]", category.id, params[:category_ids]&.include?(category.id.to_s), id: dom_id(category) %>
                    <%= label_tag dom_id(category), category.name %>
                    </div>
                <% end %>
            </div>
        
            <%= submit_tag "Filtrera", class: "primary-cta" %>
        </div>
    </div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <% if task.errors.any? %>
        <div style="color: red">

          <ul>
            <% task.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.label :title, t("tasks.form.title"), style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :company, t("tasks.form.company"), style: "display: block" %>
    <%= form.text_field :company %>
  </div>

  <div>
    <%= form.label :city, t("tasks.form.city"), style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :description, t("tasks.form.description"), style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div class="field">
    <%= form.label :categories %>
    
    <br>
    
    <% Category.all.each do |category| %>
      <div>
        <%= check_box_tag "task[category_ids][]", category.id, @task.categories.include?(category), id: dom_id(category) %>
        <%= label_tag dom_id(category), category.name %>
      </div>
    <% end %>
  </div>

  <p>eller</p>

  <div class="field">
    <%= form.label :new_category_name, "Ny kategori (frivilligt)" %>
    <%= form.text_field :new_category_name %>
  </div>

  <div>
    <%= form.submit class: "primary-cta" %>
  </div>
<% end %>

app/views/tasks/_sorting.html.erb
# TODO: figure out the logic way to display these links
<div class="sorting-links">
  <%= link_to "Äldst först", tasks_path(sort: "asc", category_ids: params[:category_ids]), class: "old-link"%>
  <%= link_to "Nyast först", tasks_path(sort: "desc", category_ids: params[:category_ids]), class: "new-link" %>
</div>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>" class="container task-wrapper">
  <div>
    <span class="show-task-label"><%= t("tasks.task.title") %>:</span>
    <span><%= task.title %></span>
  </div>

  <div>
    <span class="show-task-label"><%= t("tasks.task.company") %>:</span>
    <%= task.company %>
  </div>

  <div>
    <span class="show-task-label"><%= t("tasks.task.city") %>:</span>
    <%= task.city %>
  </div>

  <div>
    <span class="show-task-label"><%= t("tasks.task.description") %>:</span>
    <%= task.description %>
  </div>

  <div>
    <span class="show-task-label"><%= t("tasks.task.created_by") %>:</span>
    <%= task.user.email %>
  </div>

  <% if task.categories.present? %>
    <div class="task-categories-wrapper"> 
      <% task.categories.each do |category| %>
        <span class="task-category-wrapper"><%= category.name %></span>
      <% end %>
    </div>
  <% end %>

  <%= form_with url: register_task_path(@task), method: :post do %>
    <%= button_tag "Anmäl mig", class: "primary-cta" %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<% content_for :title, "#{ApplicationHelper::BRAND_NAME} | #{t('tasks.edit.page_title')}" %>

<div class="primary-background container">
  <% content_for :title, t("tasks.edit.page_title") %>
  <h1 class="secondary-heading"><%= t("tasks.edit.heading") %></h1>

  <%= form_with(model: @task) do |form| %>
    <div>
      <%= form.label :title, "Uppdragets titel" %>
      <%= form.text_field :title %>
    </div>
    <div>
      <%= form.label :company, "Företag" %>
      <%= form.text_field :company %>
    </div>
    <div>
      <%= form.label :city, "Stad" %>
      <%= form.text_field :city %>
    </div>

    <div>
      <%= form.label :categories, "Befintliga kategorier" %>
      <br>
      <% Category.all.each do |category| %>
        <div>
          <%= check_box_tag "task[category_ids][]", category.id, @task.categories.include?(category), id: dom_id(category) %>
          <%= label_tag dom_id(category), category.name %>
        </div>
      <% end %>
    </div>

    <div>
      <%= form.label :new_category_name, "Eller skapa en ny kategori" %>
      <%= form.text_field :new_category_name %>
    </div>
      
    <div class="cta-horizontal-wrapper">
      <%= form.submit "Uppdatera uppdrag", class: "primary-cta"%>
      <%= link_to t("tasks.edit.back_link"), tasks_path, class: "primary-cta" %>
    </div>
  <% end %>

</div>

app/views/tasks/index.html.erb
<% content_for :title, "#{ApplicationHelper::BRAND_NAME} | #{t('tasks.index.page_title')}" %>

<h1 class="primary-heading">Hitta volontäruppdrag</h1>

<details class="filter-sorting-wrapper">
  <summary class="filter-sorting-heading">Visa filtrering och sortering</summary>
  <%= render "tasks/sorting" %>
  <%= render "tasks/filter" %>
</details>

<div class="primary-background container">


<h2 class="secondary-heading"><%= t("tasks.index.heading", count: @pagy.count) %></h2>

  <div class="task-grid-wrapper">
    <div class="tasks-grid">
    
    <% @tasks.each do |task| %>
      <div class="task-card">
      
        <div>
          <p class="task-company"><%= task.company %></p>
          
          <h2 class="task-title"><%= task.title %></h2>
        </div>
        
        <div class="task-info-wrapper">
          <div>
            <p class="task-city">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="inherit" style="flex-shrink:0">
              <path d="M12.0001 14C14.2061 14 16.0001 12.206 16.0001 10C16.0001 7.794 14.2061 6 12.0001 6C9.79406 6 8.00006 7.794 8.00006 10C8.00006 12.206 9.79406 14 12.0001 14ZM12.0001 8C13.1031 8 14.0001 8.897 14.0001 10C14.0001 11.103 13.1031 12 12.0001 12C10.8971 12 10.0001 11.103 10.0001 10C10.0001 8.897 10.8971 8 12.0001 8Z" fill="#2B324C"></path>
              <path d="M11.4201 21.814C11.5893 21.9349 11.7921 21.9998 12.0001 21.9998C12.2081 21.9998 12.4108 21.9349 12.5801 21.814C12.8841 21.599 20.0291 16.44 20.0001 10C20.0001 5.589 16.4111 2 12.0001 2C7.58909 2 4.00009 5.589 4.00009 9.995C3.97109 16.44 11.1161 21.599 11.4201 21.814ZM12.0001 4C15.3091 4 18.0001 6.691 18.0001 10.005C18.0211 14.443 13.6121 18.428 12.0001 19.735C10.3891 18.427 5.97909 14.441 6.00009 10C6.00009 6.691 8.69109 4 12.0001 4Z" fill="#2B324C"></path>
              </svg>
              
              <%= task.city %>
            </p>
          </div>

            <% if task.categories.present? %>
              <div class="task-categories-wrapper"> 
                <% task.categories.each do |category| %>
                  <span class="task-category-wrapper"><%= category.name %></span>
                <% end %>
              </div>
            <% end %>

          <p class="task-creator"><%= t("tasks.index.created_by", email: task.user.email) %></p>
            
          <div class="task-card-actions-wrapper">
            <%= link_to t("tasks.task.read_more"), task_path(task), class: "read-more-link" %>

            <% if user_signed_in? %>  
              <div class="task-card-buttons">  
                <div>
                  <%= link_to edit_task_path(task) do %>
                    <svg class="edit-svg" viewBox="0 0 24 24" fill="none">
                      <path d="M21.2799 6.40005L11.7399 15.94C10.7899 16.89 7.96987 17.33 7.33987 16.7C6.70987 16.07 7.13987 13.25 8.08987 12.3L17.6399 2.75002C17.8754 2.49308 18.1605 2.28654 18.4781 2.14284C18.7956 1.99914 19.139 1.92124 19.4875 1.9139C19.8359 1.90657 20.1823 1.96991 20.5056 2.10012C20.8289 2.23033 21.1225 2.42473 21.3686 2.67153C21.6147 2.91833 21.8083 3.21243 21.9376 3.53609C22.0669 3.85976 22.1294 4.20626 22.1211 4.55471C22.1128 4.90316 22.0339 5.24635 21.8894 5.5635C21.7448 5.88065 21.5375 6.16524 21.2799 6.40005V6.40005Z" stroke="#000000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                    <path d="M11 4H6C4.93913 4 3.92178 4.42142 3.17163 5.17157C2.42149 5.92172 2 6.93913 2 8V18C2 19.0609 2.42149 20.0783 3.17163 20.8284C3.92178 21.5786 4.93913 22 6 22H17C19.21 22 20 20.2 20 18V13" stroke="#000000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                  </svg>
                <% end %>
                </div>
                
                <div>
                  <%= form_with(url: task_path(task), method: :delete) do %>
                    <%= button_tag type: "submit", class: "delete-task-btn", onclick: "return confirm('Är du säker på att du vill radera uppdraget?');" do %>
                      <svg class="delete-svg" viewBox="0 0 1024 1024"><path fill="inherit" d="M160 256H96a32 32 0 0 1 0-64h256V95.936a32 32 0 0 1 32-32h256a32 32 0 0 1 32 32V192h256a32 32 0 1 1 0 64h-64v672a32 32 0 0 1-32 32H192a32 32 0 0 1-32-32V256zm448-64v-64H416v64h192zM224 896h576V256H224v640zm192-128a32 32 0 0 1-32-32V416a32 32 0 0 1 64 0v320a32 32 0 0 1-32 32zm192 0a32 32 0 0 1-32-32V416a32 32 0 0 1 64 0v320a32 32 0 0 1-32 32z"/></svg>
                    <% end %>
                  <% end %>
                </div>  
              </div>    
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    </div>


    <%== pagy_nav(@pagy) if @pagy.pages > 1 %>

</div>


</div>

app/views/tasks/new.html.erb
<% content_for :title, "#{ApplicationHelper::BRAND_NAME} | #{t('tasks.new.page_title')}" %>

<div class="primary-background container">
  <hgroup>
    <h1 class="secondary-heading"><%= t("tasks.new.new_task") %></h1>
    <h2>Här kan du skapa ett konto på Volontärbyrån. Med ett konto kan du spara och söka uppdrag som volontär eller lägga upp uppdrag åt din organisation. </h2>
  </hgroup>
  <div class="create-tasks-form-container">
    <%= render "form", task: @task %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="primary-background container">
  <h1 class="secondary-heading"><%= notice %></h1>

  <%= render @task %>

  <div class="cta-vertical-wrapper">
    <div class="cta-horizontal-wrapper">
      <%= link_to t("tasks.show.edit_link"), edit_task_path(@task), class: "primary-cta" %>
      <%= button_to t("tasks.show.destroy_link"), @task, method: :delete, class: "primary-cta" %>
      </div>
      
      <%= link_to t("tasks.show.back_link"), tasks_path, class: "primary-cta" %>
  </div>
</div>